### PR TITLE
Hello Microverse 

### PR DESCRIPTION
**Pull request by 0sugo**
In this PR, I did the following:

Added the index.html file.
Added the style.css file.
Added the linters file.
Added the test.md file to the .gitignore file.
Ensured there was no linter error

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @0sugo 
### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7




## Highlights
 - [ ]  Correct GitHub Flow  ✅
 - [ ]  All linters passed  ✅
 
## Required Changes ♻️
 - [x] I see you have an empty readme file, This will affect your professionality as a developer. We need to use a professional readme file in all our projects and for that [Microverse provides a Readme template](https://github.com/microverseinc/readme-template) we can customize and use it. I suggest you do the same before the next review request.

_Check the comments under the review._

## Optional suggestions
- [Optional] Please try to be more descriptive in your pull request, This is the place to tell your code reviewers what you did in detail.
- [Optional] I notice some of your changes (.gitignor and README) are already on the main branch, This is not a good practice as it will not be transparent for your reviewer about what exactly changed in this pull request. 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by 0sugo** [comment]
Hello @Tadesse-Alemayehu , I have made some changes regarding  the readme file ,Kindly take a look and let me know if its okay.

**Comment by TadesseDev** [comment]
Dear @0sugo, Please include all the details in the [Microverse provides a Readme template](https://github.com/microverseinc/readme-template) and customize the contents. 🙌

**Comment by 0sugo** [comment]
Hi @Tadesse-Alemayehu sorry about the back and forth thing,But I have corrected on the readme.I would appreciate if you spent sometime to have a look.Thanks

**Review by algerina — APPROVED** [review]
Hi @0sugo  ,

Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:



 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

**Comment by 0sugo** [comment]
Thanks @algerina  and @Tadesse-Alemayehu  for your guidance

**Pull request merged**
